return {
    -- No config plugins go here
  'https://gitlab.com/HiPhish/rainbow-delimiters.nvim',
  -- 'nvim-tree/nvim-web-devicons',
  'nvimtools/none-ls-extras.nvim',
  'cappyzawa/trim.nvim',
  'Tastyep/structlog.nvim',
  'nvim-telescope/telescope-symbols.nvim',
  'debugloop/telescope-undo.nvim',
  'nvim-telescope/telescope-ui-select.nvim',
  'nvim-telescope/telescope-frecency.nvim',
  'nvim-telescope/telescope-dap.nvim',
  'onsails/lspkind.nvim',
  'hrsh7th/cmp-path',
  'hrsh7th/cmp-buffer',
  'petertriho/cmp-git',
  'hrsh7th/cmp-nvim-lsp',
  'hrsh7th/cmp-nvim-lsp-signature-help',
  'rcarriga/cmp-dap',
  'tamago324/nlsp-settings.nvim',
  'udalov/kotlin-vim',
  'hrsh7th/cmp-nvim-lua',
  'JMarkin/cmp-diag-codes',
  'David-Kunz/cmp-npm',
  'Snikimonkd/cmp-go-pkgs',
  'vrslev/cmp-pypi',
  'ray-x/cmp-sql',
  'sbdchd/neoformat'
}
