return {
    -- No config plugins go here
  'hiphish/rainbow-delimiters.nvim',
  -- 'nvim-tree/nvim-web-devicons',
  'nvimtools/none-ls-extras.nvim',
  'Tastyep/structlog.nvim',
  'nvim-telescope/telescope-symbols.nvim',
  'debugloop/telescope-undo.nvim',
  'nvim-telescope/telescope-ui-select.nvim',
  'nvim-telescope/telescope-frecency.nvim',
  'nvim-telescope/telescope-dap.nvim',
  'LukasPietzschmann/telescope-tabs',
  'Marskey/telescope-sg',
  'onsails/lspkind.nvim',
  'hrsh7th/cmp-path',
  'hrsh7th/cmp-buffer',
  'hrsh7th/cmp-nvim-lsp',
  'hrsh7th/cmp-nvim-lsp-signature-help',
  'rcarriga/cmp-dap',
  'petertriho/cmp-git',
  'samiulsami/cmp-go-deep',
  'https://git.sr.ht/~amaral/nvim-cmp-buffer-lines',
  'udalov/kotlin-vim',
  'hrsh7th/cmp-nvim-lua',
  'JMarkin/cmp-diag-codes',
  'David-Kunz/cmp-npm',
  'Snikimonkd/cmp-go-pkgs',
  'vrslev/cmp-pypi',
  'ray-x/cmp-sql',
  'sbdchd/neoformat',
  'direnv/direnv.vim',
  'stevearc/vim-vscode-snippets',
  'kkharji/sqlite.lua'
}
