--- @diagnostic disable: annotation-usage-error
---@module 'lazy'

return  --[[@type LazyPluginSpec]]{
  -- No config plugins go here
  -- 'nvim-tree/nvim-web-devicons',
  'nvimtools/none-ls-extras.nvim',
  'Tastyep/structlog.nvim',
  'nvim-telescope/telescope-symbols.nvim',
  'debugloop/telescope-undo.nvim',
  'nvim-telescope/telescope-ui-select.nvim',
  'nvim-telescope/telescope-frecency.nvim',
  'nvim-telescope/telescope-dap.nvim',
  'LukasPietzschmann/telescope-tabs',
  'Marskey/telescope-sg',
  'onsails/lspkind.nvim',
  'hrsh7th/cmp-path',
  'hrsh7th/cmp-buffer',
  'hrsh7th/cmp-nvim-lsp',
  'rcarriga/cmp-dap',
  'petertriho/cmp-git',
  'udalov/kotlin-vim',
  'hrsh7th/cmp-nvim-lua',
  'JMarkin/cmp-diag-codes',
  'David-Kunz/cmp-npm',
  'vrslev/cmp-pypi',
  'ray-x/cmp-sql',
  'sbdchd/neoformat',
  'direnv/direnv.vim',
  'stevearc/vim-vscode-snippets',
  'kkharji/sqlite.lua',
  'tpope/vim-repeat',
  'RRethy/nvim-treesitter-endwise',
  'nickel-lang/vim-nickel',
}
